### PR TITLE
Allow dart-reddit to work on flutter

### LINKED ISSUE #11: Replacing Mirror Delegation for Flutter
I have a working version of this code that removes the mirrors and JsonObjects. This allows the code to run in Flutter applications without issue.

I have not posted this yet because I am not sure how to replace your ListingResult::noSuchMethod 
```dart
  @override
  noSuchMethod(Invocation inv) => reflect(_result).delegate(inv);
```

I need to return something else instead of the reflect call.  If you have thoughts on what to do with this I'd greatly appreciate it.

### PR DESCRIPTION
**Pull request by mrdjohnson**
fixes #11 
Replaced instances of JsonObject and mirrors to allow  with convert:JSON and Maps library to run on the flutter platform (only tested on android)

### CODE REVIEW

**Comment by stevenroose** [comment]
I don't think this will work. Implementing the Map interface means that you need to have a lot of methods. F.e. the Map method `forEach(function)` will not get mapped to `_result["forEach"]`, which will break the Map interface. I think there is a class you can extend `MapBase` so that you only have to implement a few abstract methods, that you can manually forward to `_result` and then you can drop the `noSuchMethod`.

**Comment by mrdjohnson** [comment]
After looking at the OTHER pull request, I am pretty sure that we have the same (if not very similar) code , with the only difference being mine getting rid of mirrors call.

**Comment by stevenroose** [comment]
Oh, I forgot about the other PR. [This part](https://github.com/stevenroose/dart-reddit/pull/9/files#diff-b7b5bde764df26dc204f7cbc908692a6R91) is what I meant with using the `MapBase` (seemingly `MapMixin` class), while [these](https://github.com/stevenroose/dart-reddit/pull/9/files#diff-b7b5bde764df26dc204f7cbc908692a6R100) are the different methods the mixin class requires you to implement. 

I think I can just remove the mirrors import on the other PR, would that work for you?

**Comment by mrdjohnson** [comment]
Works for me.

**Comment by stevenroose** [comment]
Take a look: https://github.com/stevenroose/dart-reddit/pull/9

**Comment by rodydavis** [comment]
Is there an update on this? I am excited about using this for flutter!

**Comment by stevenroose** [comment]
@AppleEducate, can you check if #9 works for you? I think it should be finished, but I'd like some confirmation.

**Comment by rodydavis** [comment]
@stevenroose That works!

**Comment by stevenroose** [comment]
Superseded by https://github.com/stevenroose/dart-reddit/pull/9.

**Pull request closed without merging**
