### PR TITLE
Subreddit.search() should be contextual to the sub

### PR DESCRIPTION
**Pull request by SecareLupus**
Subreddit.search() currently searches all of reddit, regardless of what subreddit object it is called on. If search() is a member function of Subreddit, it should be searching that subreddit specifically.

### CODE REVIEW

**Comment by stevenroose** [comment]
Thanks for the PR!

However, I think, that setting the `restrict_sr` parameter to `true`, see [here](https://www.reddit.com/dev/api/#section_search).

Mind to change that? Just add `"restrict_sr": true` to the map in the query constructor and remove the `subreddit:` from the query.

**Comment by SecareLupus** [comment]
I didn't realize the search hitting all the subs was a reflection of the actual api. I updated my code to use the restrict_sr flag, and as my commit msg says, I made it an optional parameter on the search() function. Don't know if that is within design style for your library, but it made the most sense to me. If that's wrong, lemme know and I'll make further changes.

**Comment by stevenroose** [comment]
No, it was an overlook. I agree that it doesn't make sense to search globally when hitting search on a sub. I would personally not even have the parameter.

If you want, you can remove it. Otherwise, I'll wait until tomorrow and merge it and remove it myself.

Many thanks, it's nice to see some fellow Dart-loving Redditors around :)

**Comment by SecareLupus** [comment]
going to refork with a single commit for a cleaner merge.

**Comment by stevenroose** [comment]
You could rewrite the history and force push the branch with `git push -
f`. Just for the record so you know for next time.

**Pull request closed without merging**
